version: 0.2
phases:
  install:
    commands:
      - echo Entered the install phase...
      # Install jq
      - apt-get update && apt-get install -y curl jq
  build:
    commands:
      - aws s3 cp index.html s3://lou-lpool-web-123
      - aws s3 cp img/ s3://lou-lpool-web-123/img --recursive
  post_build:
    commands:
      - echo Invalidating distribution
      # Find the distribution ID for the one with an alias which contains a common token in each environment
      - export DISTRIBUTION_ID=$(aws cloudfront list-distributions | jq --raw-output '.CloudFrontOriginAccessIdentityList.Items[] | select(.DomainName contains "lpool").Id')
      # Invalidate Cache
      - echo "Invalidating CloudFront cache with Distribution ID:" ${DISTRIBUTION_ID}
      - aws cloudfront create-invalidation --distribution-id EKLW74X46Q5BB --paths "/*"

artifacts:
  files:
    - "**/*"
